  #setting up frontend
   # install Nginx
    #install a dnf package collection
  #Remove the default content that webserver is serving means we delete the directory
  #create the file which you just deleted

  #Placing Expense Config File in Nginx
  #Download and extract and unzip the file the frontend file which is saved on the remote location
  #start and enable Nginx

#- name: Frontend setup
#  hosts: all
#  become: yes
#  tasks:

      - name: set hostname
        ansible.builtin.shell: set-hostname frontend
      - name: Installing Nginx
        ansible.builtin.dnf:
          name: nginx
          state: installed

      - name: Placing Expense Config File in Nginx
        ansible.builtin.template:
          src: expense.conf
          dest: /etc/nginx/default.d/expense.conf

      - name: Update Nginx Config
        ansible.builtin.template:
            src: nginx.conf
            dest: /etc/nginx/nginx.conf

#      - name: Removing old Nginx content(deleting the directory)
#        ansible.builtin.file:
#          path: /usr/share/nginx/html
#          state: absent
#
#      - name: creating Nginx content directory
#        ansible.builtin.file:
#          path: /usr/share/nginx/html
#          state: directory
#
#      - name: Download frontend code and extract frontend code
#        ansible.builtin.unarchive:
#          src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
#          dest: /usr/share/nginx/html
#          remote_src: yes


      - name: Include App Pre-requisites
        ansible.builtin.import_role:
          name: common
          tasks_from: app_prerequisites


      - name: Starting Nginx Service
        ansible.builtin.systemd:
          name: nginx.service
          state: restarted
          enabled: yes
         # remote_src: yes
      - name: install filebeat
        ansible.builtin.import_role:
          name: elk
          tasks_from: filebeat












