- name: copy prometheus
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
#    enable: yes



- name: copy prometheus record file
  ansible.builtin.template:
    src: record.yml
    dest: /opt/prometheus/record.yml


- name: copy prometheus record file
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml